services:
  - type: web
    name: n8n
    env: docker
    plan: free
		autoDeploy: true
    branch: main
    buildCommand: ""
    startCommand: "n8n start"
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: M8nchick
      - key: N8N_BASIC_AUTH_PASSWORD
        value: techtink30
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-vixen.onrender.com
